### ISSUE TITLE
Coverage is broken

### ISSUE THREAD

**Issue by Sorunome** [demurgos/turbo-gulp#163]
```
SourceMapReadError: { scriptUrl: 'file:///home/sorunome/repos/skype-http/node_modules/async-file/index.js', sourceMapUrl: 'file:///home/sorunome/repos/skype-http/node_modules/async-file/index.js.map' }
[15:53:07] 'test:coverage:cjs' errored after 16 s
[15:53:07] CoverageError: { args: [ '--reporter', 'text', '--reporter', 'lcov-file', '--reporter', 'html', '--color', '--', '/usr/bin/node', '/home/sorunome/repos/skype-http/node_modules/turbo-gulp/node_modules/mocha/bin/mocha', '--ui', 'bdd', '--reporter', 'spec', '--colors', '/home/sorunome/repos/skype-http/build/test/test.cjs.js' ] }
[15:53:07] 'test' errored after 21 s
````
It seems that c88 tries to read a non-existing .js.map from an external module, for whatever reason?

**Comment by demurgos** [comment]
Hi,
This library was started around 2015 to help manage the config of various tools. Now that Typescript supports project references, Node has native ESM support, Yarn handles workspaces and various other improvements, I reached a point were I feel this library is no longer pulling its weight and I am starting to deprecate it and recommend converting the project to use regular CLI commands in the `scripts`  section of `package.json`.

I see that your issue comes from `skype-http`. I am no longer maintaining this library, if you are still interesting in it I recommend to use the source-code as inspiration, but maybe write your own Skype client.

Regarding the specific issue, I am not sure why it tries to read the source-map you posted. `c88` is another personal library I created, mostly to experiment on alternative design to address some flaws of `c8`. `c8` is still a great library and I recommend using it (or nyc) directly for your own projects. I'll look into making it more reliable and fix this issue eventually, but it's not a high priority.

Thanks for the report, unfortunately I don't plan on actively fixing it (unfortunately I don't have enough time to work on it). I hope you understand.

**Comment by Sorunome** [comment]
Thank you for the quick reply! Your reasoning does make sense, I didn't stumble upon turbo-gulp prior to messing with skype-http yet, anyways.

> I see that your issue comes from `skype-http`. I am no longer maintaining this library, if you are still interesting in it I recommend to use the source-code as inspiration, but maybe write your own Skype client.

You might be happy to hear that I picked up the library, got it to work again and added support for more things (like message edits, contact updates etc.)
